### ISSUE TITLE
babyに実行権限が欲しいかもしれません

### ISSUE THREAD

**Issue by tam1192** [somakai-sumasi/mountain#1]
元ツイートでは `./baby` となっています。
そのため、tar -xf momo.tar
の中身は
```diff
- baby.sh
+ baby
```
であり、さらに実行権限
```bash
chmod +x baby
```
が必要だと思います。

とはいえ面白かったです！
ありがとうございます。

**Comment by somakai-sumasi** [comment]
やっつけ仕事なので仕事が荒かったです...
最新では修正してます!
